# Generated by Django 5.1.5 on 2025-01-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracker', '0005_remove_timeentry_tags_timeentry_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='tags',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='tags',
            field=models.ManyToManyField(blank=True, to='timetracker.tag'),
        ),
    ]
